# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import webapps.buildinginfos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building_Zone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_nickname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'building_zone',
            },
        ),
        migrations.CreateModel(
            name='BuildingMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmap_file_location', models.ImageField(upload_to=webapps.buildinginfos.models.get_file_path)),
            ],
            options={
                'db_table': 'building_map',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_setpoint', models.IntegerField(blank=True, null=True)),
                ('cool_setpoint', models.IntegerField(blank=True, null=True)),
                ('illuminance', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildinginfos.Building_Zone')),
            ],
            options={
                'db_table': 'global_zone_setting',
            },
        ),
    ]
