# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deviceinfos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_modified', models.DateTimeField()),
                ('device_model', models.ForeignKey(db_column=b'device_model', on_delete=django.db.models.deletion.CASCADE, to='deviceinfos.SupportedDevices')),
            ],
            options={
                'db_table': 'passwords_manager',
            },
        ),
    ]
