# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multinode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetadata',
            fields=[
                ('agent_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50, null=True)),
                ('device_model', models.CharField(max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('min_range', models.IntegerField(blank=True, null=True)),
                ('max_range', models.IntegerField(blank=True, null=True)),
                ('identifiable', models.BooleanField(default=False)),
                ('authorizable', models.BooleanField(default=False)),
                ('communication', models.CharField(max_length=20, null=True)),
                ('date_added', models.DateTimeField(null=True)),
                ('factory_id', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_status', models.CharField(choices=[(b'APR', b'Approved'), (b'PND', b'Pending'), (b'NBD', b'Non-BEMOSS Device')], default=b'PND', max_length=20)),
            ],
            options={
                'db_table': 'device_info',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'miscellaneous',
            },
        ),
        migrations.CreateModel(
            name='SupportedDevices',
            fields=[
                ('device_model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('communication', models.CharField(max_length=10)),
                ('api_name', models.CharField(max_length=50)),
                ('html_template', models.CharField(max_length=50)),
                ('chart_template', models.CharField(max_length=50, null=True)),
                ('agent_type', models.CharField(default=b'BasicAgent', max_length=50)),
                ('identifiable', models.BooleanField()),
                ('authorizable', models.BooleanField(default=False)),
                ('is_cloud_device', models.BooleanField(default=False)),
                ('schedule_weekday_period', models.IntegerField(blank=True)),
                ('schedule_weekend_period', models.IntegerField(blank=True)),
                ('allow_schedule_period_delete', models.BooleanField()),
                ('address', models.CharField(default=b'None', max_length=300, null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceinfos.DeviceType')),
            ],
            options={
                'db_table': 'supported_devices',
            },
        ),
        migrations.AddField(
            model_name='devicemetadata',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceinfos.DeviceType'),
        ),
        migrations.AddField(
            model_name='devicemetadata',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multinode.NodeInfo'),
        ),
    ]
