# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 18:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRegistered',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('app_folder', models.CharField(max_length=200)),
                ('registered_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'application_registered',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('app_agent_id', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('app_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemoss_applications.ApplicationRegistered')),
            ],
            options={
                'db_table': 'application_running',
            },
        ),
    ]
