# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDeviceStatus',
            fields=[
                ('agent_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_move', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_device',
            },
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=20)),
                ('node_type', models.CharField(blank=True, max_length=20, null=True)),
                ('node_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_scanned_time', models.DateTimeField(blank=True, null=True)),
                ('last_offline_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('node_resources_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_info',
            },
        ),
        migrations.AddField(
            model_name='nodedevicestatus',
            name='assigned_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NodeDevice_previous', to='multinode.NodeInfo'),
        ),
        migrations.AddField(
            model_name='nodedevicestatus',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NodeDevice_current', to='multinode.NodeInfo'),
        ),
    ]
