# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deviceinfos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicedata',
            fields=[
                ('agent', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='deviceinfos.DeviceMetadata')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('dashboard_view', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('network_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_scanned_time', models.DateTimeField(blank=True, null=True)),
                ('last_offline_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devicedata',
            },
        ),
    ]
