# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_reason', models.CharField(help_text='Reason for the ban?', max_length=255)),
                ('type', models.CharField(choices=[('ip-address', 'IP Address'), ('user-agent', 'User Agent')], default=0, help_text='Type of User Ban to store', max_length=20)),
                ('condition', models.CharField(help_text='Enter an IP to ban/whitelist, or a User Agent string to ban', max_length=255)),
            ],
            options={
                'db_table': 'banishments',
                'verbose_name': 'Banishment',
                'verbose_name_plural': 'Banishments',
                'permissions': (('can_ban_user', 'Can Ban User'),),
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_reason', models.CharField(help_text='Reason for the whitelist?', max_length=255)),
                ('type', models.CharField(choices=[('ip-address-whitelist', 'Whitelist IP Address')], default=0, help_text='Enter an IP address to whitelist', max_length=20)),
                ('condition', models.CharField(help_text='Enter an IP to whitelist', max_length=255)),
            ],
            options={
                'db_table': 'whitelists',
                'verbose_name': 'Whitelist',
                'verbose_name_plural': 'Whitelists',
                'permissions': (('can_whitelist_user', 'Can Whitelist User'),),
            },
        ),
    ]
